# Use Node.js as a base
FROM node:18

# Defines the working directory inside the container
WORKDIR /app

# Copy the project configuration files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the microservice code
COPY . .

# Expose the port defined in the .env file
EXPOSE ${PORT}

# Load environment variables and run the service
CMD ["sh", "-c", "node server.js"]