# Usar una imagen base de Node.js
FROM node:20

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Exponer el puerto del API Gateway
EXPOSE ${PORT}

# Comando para ejecutar el API Gateway
CMD ["node", "server.js"]
