# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: carousel.proto

require 'google/protobuf'


descriptor_data = "\n\x0e\x63\x61rousel.proto\x12\x08\x63\x61rousel\"\x0e\n\x0c\x45mptyRequest\"\x1c\n\x0eImageIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\rCarouselImage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\timage_url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\"D\n\x19\x43\x61rouselImageListResponse\x12\'\n\x06images\x18\x01 \x03(\x0b\x32\x17.carousel.CarouselImage\"W\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x10\n\x08\x64iscount\x18\x05 \x01(\x02\":\n\x13ProductListResponse\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.carousel.Product2\xb5\x01\n\x0f\x43\x61rouselService\x12P\n\x11GetCarouselImages\x12\x16.carousel.EmptyRequest\x1a#.carousel.CarouselImageListResponse\x12P\n\x15GetDiscountedProducts\x12\x18.carousel.ImageIdRequest\x1a\x1d.carousel.ProductListResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Carousel
  EmptyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("carousel.EmptyRequest").msgclass
  ImageIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("carousel.ImageIdRequest").msgclass
  CarouselImage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("carousel.CarouselImage").msgclass
  CarouselImageListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("carousel.CarouselImageListResponse").msgclass
  Product = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("carousel.Product").msgclass
  ProductListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("carousel.ProductListResponse").msgclass
end
