# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: carousel.proto for package 'carousel'

require 'grpc'
require 'carousel_pb'

module Carousel
  module CarouselService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'carousel.CarouselService'

      # Devuelve la lista de imágenes del carrusel
      rpc :GetCarouselImages, ::Carousel::EmptyRequest, ::Carousel::CarouselImageListResponse
      # Devuelve los productos en oferta al hacer clic en una imagen
      rpc :GetDiscountedProducts, ::Carousel::ImageIdRequest, ::Carousel::ProductListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
