name: 🚀 Deploy Category Delete Service to AWS

on:
  push:
    paths:
      - 'Backend_uceShoes/productManagement/productCreation/Category/deleteCategory/**'
    branches:
      - TestConectionProducts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout del repositorio
        uses: actions/checkout@v4

      - name: 🔧 Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Iniciar sesión en Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 📦 Construir y subir imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/category-delete:latest \
            -f Backend_uceShoes/productManagement/productCreation/Category/deleteCategory/Dockerfile \
            Backend_uceShoes/productManagement/productCreation/Category/deleteCategory

          docker push ${{ secrets.DOCKER_USERNAME }}/category-delete:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: 🚀 Connect to EC2 and Deploy Category Delete Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_DELETE_CATEGORY }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "🔍 Checking if Docker is installed..."
            if ! command -v docker &> /dev/null; then
              echo "📦 Installing Docker..."
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo usermod -a -G docker $USER
            fi

            echo "🛑 Stopping and removing previous container..."
            if sudo docker ps -q -f name=category-delete; then
              sudo docker stop category-delete
              sudo docker rm category-delete
            else
              echo "⚠️ No running container found."
            fi

            echo "🧹 Removing old Docker images..."
            sudo docker image prune -af || echo "⚠️ No images to remove."

            echo "📥 Pulling the latest Docker image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/category-delete:latest

            echo "🚀 Running the new container..."
            sudo docker run -d \
              --name category-delete \
              -p ${{ secrets.SERVER_PORT_DELETE_CATEGORY }}:${{ secrets.SERVER_PORT_DELETE_CATEGORY }} \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/category-delete:latest

            echo "🔍 Verifying deployment..."
            if sudo docker ps -q -f name=category-delete; then
              echo "✅ Deployment successful: Category Delete Service is running."
            else
              echo "❌ Deployment failed: Check logs for errors."
              exit 1
            fi 

      - name: 🔐 Log out of Docker Hub
        run: docker logout