name: 🚀 Deploy Category Create Service to AWS

on:
  push:
    paths:
      - 'Backend_uceShoes/productManagement/productCreation/Category/createCategory/**'
    branches:
      - TestConectionProducts

jobs:
  build-and-deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 📦 Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/category-create:latest \
            -f Backend_uceShoes/productManagement/productCreation/Category/createCategory/Dockerfile \
            Backend_uceShoes/productManagement/productCreation/Category/createCategory

          docker push ${{ secrets.DOCKER_USERNAME }}/category-create:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: 🚀 Connect to EC2 and Deploy Category Create Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_CREATE_CATEGORY }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "🔍 Checking if Docker is installed..."
            if ! command -v docker &> /dev/null; then
              echo "📦 Installing Docker..."
              sudo yum update -y
              sudo yum install -y docker
              sudo service docker start
              sudo usermod -a -G docker $USER
            fi

            echo "🛑 Stopping and removing previous container..."
            sudo docker stop category-create || true
            sudo docker rm category-create || true

            echo "🧹 Removing old Docker images..."
            sudo docker image prune -af

            echo "📥 Pulling the latest Docker image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/category-create:latest

            echo "🚀 Running the new container..."
            sudo docker run -d \
              --name category-create \
              -p ${{ secrets.SERVER_PORT_CREATE_CATEGORY }}:${{ secrets.SERVER_PORT_CREATE_CATEGORY }} \
              -e PORT=${{ secrets.SERVER_PORT_CREATE_CATEGORY }} \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -e DB_DIALECT=postgres \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/category-create:latest

            echo "🔍 Verifying deployment..."
            if sudo docker ps -q -f name=category-create | grep category-create; then
              echo "✅ Deployment successful: Category Create Service is running."
            else
              echo "❌ Deployment failed: Fetching logs..."
              sudo docker logs category-create
              exit 1
            fi